### ISSUE TITLE
Enhance /version text ingame

### ISSUE THREAD

**Issue by WouterG** [SpleefLeague/Core#12]
The /version command output gets pretty messy with all the [SpleefLeague] prefixes, empty lines and weird word-wraps, and I think we could easily display the same information in a smaller space that fits the chat better.

[preview of current output on my monitor](http://i.imgur.com/E24sshU.png)

**Comment by Jobarion** [comment]
Also, maybe not use yellow and green together, since that's hard to distinguish for colorblind people

**Comment by RinesThaix** [comment]
Resolved in https://github.com/SpleefLeague/Core/commit/79d85a285c531317020d50fdaae69261b52263e0
