### ISSUE TITLE
Allow AFK'ing for second donator tier and up

### ISSUE THREAD

**Issue by WouterG** [SpleefLeague/Core#7]
I'm not sure if AFK'ing get's you kicked, but if it does the kick system should be disabled for the donator ranks `$$` and `$$$`.

> forward from Onespoone #devchat

**Comment by RinesThaix** [comment]
Implemented it in https://github.com/SpleefLeague/Core/commit/3d6160e0ea9a5f3a7f1a110e105041df303da40c
